min_version = "2024.9.5"

[tools]
python = "3.12"

[env]
_.path = ["{{env.HOME}}/.krew/bin"]
_.python.venv = {path = ".venv", create=true}

# This auto-updates tools and plugins
[hooks]
enter = "mise self-update && mise i -q && mise upgrade --bump && mise plugins update"
cd = "mise self-update && mise i -q && mise upgrade --bump && mise plugins update"

[tasks]

[tasks.lint]
description = "Lint with ruff check"
alias = "ruff"
run = "ruff check ."

[tasks.test]
description = "test with pytest"
alias = "pytest"
run = "pytest tests/"
