[tools]
node = 'latest'
python = ["3.12", "3.13", "3.12", "3.11"]
bun = "latest"
"npm:prettier" = "latest"
"npm:remark-cli" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:commitlint" = "latest"
"pipx:icloudpd" = { version = "latest" } # , extras = "postgres,s3" 
"pipx:black" = "latest"
"pipx:ruff" = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:hexyl" = "latest"
"cargo:jless" = "latest"
"cargo:git-cliff" = "latest"
"cargo:git-absorb" = "latest"

# toml syntax check + formatter
taplo = "latest"
markdownlint-cli2 = "latest"
shfmt = "latest"
shellcheck = "latest"
yamlfmt = "latest"
yamllint = "latest"
#"npm:renovate" = "latest"
#"npm:cspell" = "latest"
typos = "latest"
watchexec = "latest"
grex = "latest"
chezmoi = "latest"
difftastic = "latest"

"pipx:pipreqs" = "latest"
"pipx:dataclass-wizard" = "latest"
"pipx:tach" = "latest"
"aqua:errata-ai/vale" = "latest"
uv = { version = "latest", postinstall = "uv --generate-shell-completion zsh > $HOME/.local/share/zinit/completions/_uv && autoload -Uz compinit && compinit -u" }
"pipx:ansible-lint" = "latest"
"go:github.com/dimonomid/nerdlog/cmd/nerdlog" = "latest"
"pipx:git+https://github.com/mschuett/yaml-shellcheck.git" = "v1.6.0"
"pipx:vcstool" = "latest"
"pipx:validate-pyproject" = "latest"
"pipx:ssh-para" = "latest"
"pipx:setuptools-py2cfg" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pipdeptree" = "latest"
"pipx:pip-upgrader" = "latest"
"pipx:gitlab-ci-verify-bin" = "latest"
"pipx:paperless-asn-qr-codes" = "latest"
"pipx:git-cliff" = "latest"
"pipx:cuvner" = "latest"
"pipx:cruft" = "latest"
"pipx:commitizen" = "latest"
"pipx:check-jsonschema" = "latest"
"pipx:ansible-doc-extractor" = "latest"

"pipx:tern" = { version = "latest", uvx_args = "--python 3.11"}
"pipx:csvkit" = "latest"
cosign = "latest"
"pipx:tldr" = "latest"
rust = "latest"

[tools.rg]
version = "latest"
postinstall = "rg --generate=complete-zsh > $HOME/.local/share/zinit/completions/_rg && autoload -Uz compinit && compinit -u"

[tools.fd]
version = "latest"
postinstall = "fd --gen-completions=zsh > $HOME/.local/share/zinit/completions/_fd && autoload -Uz compinit && compinit -u"
[tools."cargo:broot"]
version = "latest"
postinstall = "broot --print-shell-function zsh > $HOME/.config/broot/launcher/bash/br && source $HOME/.config/broot/launcher/bash/br"

[hooks]
enter = "mise i -q && mise plugins update"

[settings]
jobs = 1
experimental = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[settings.python]
uv_venv_auto = true
