# https://github.com/catppuccin/fnott/blob/main/themes/catppuccin-mocha.ini

title-color=a6adc8ff
summary-color=cdd6f4ff
body-color=cdd6f4ff
background=1e1e2eff
border-color=89b4faff
progress-bar-color=6c7086ff

[critical]
border-color=fab387ff
